name: GUIPlayerAuth
version: '${version}'
main: io.github.earth1283.guiplayerauth.GUIPlayerAuthPlugin
api-version: '1.21'
description: A groundbreaking, GUI-based player login system.
author: Earth1283
