name: GUIPlayerAuth
version: 2.1
main: io.github.Earth1283.gUIPlayerAuth.GUIPlayerAuth
api-version: 1.17
author: Earth1283
description: Using a GUI to authenticate players on cracked servers and online mode servers alike!
commands:
  register:
    description: Opens the registration GUI
  login:
    description: Opens the login GUI
permissions:
  guiplayerauth.use:
    description: Allows use of the authentication GUI
    default: true
